print("Clearing system")
print("------------------------------------------")
shell.run("delete TURTLE")
shell.run("delete POCKET")
shell.run("delete HUB")
shell.run("delete turtles.lua")
shell.run("delete pockets.lua")
shell.run("delete git.lua")
shell.run("delete clean.lua")
print("------------------------------------------")
print("Done")
