print("Extracting files to root")
print("------------------------------------------")
shell.run("copy TURTLE/ ..")
shell.run("copy POCKET/ ..")
shell.run("copy HUB/ ..")
print("Copied main fodl")

shell.run("copy turtles.lua ..")
shell.run("copy pockets.lua ..")
shell.run("copy clean.lua ..")
print("Copied main files")

shell.run("delete .")
print("------------------------------------------")
print("Done")
