print("Extracting files to root")
print("------------------------------------------")
shell.run("copy . ../")
shell.run("delete cc-tweaked-carpet-bomber/")
print("------------------------------------------")
print("Done")